### ISSUE TITLE
el tiempo requerido usando trafico no podria calcularse desde la api de google?

### ISSUE THREAD

**Issue by harpomaxx** [GioAzdy75/ia-uncuyo-2024#1]

**Comment by gabichulas** [comment]
Hola profe! No sé bien si se refiere a lo que serían los pesos de las aristas del grafo, pero si es así, según lo que investigamos extraer estos datos de la API de Google suponen un gasto económico, por lo que revisando bien en la documentación de la biblioteca que usaremos para manejar el grafo de la ciudad y navegando en algunos foros dimos con que, manipulando algunos datos, es posible conseguirlo.
